---
vm_location: "/home/VirtualMachines"
root_pass: "r3dh4t1!"
disk_image: "images/rhel-server-7.6-x86_64-kvm.qcow2"
prepare_image: false
force_repos: false

#size in GB
root_disk_size: "15"

reg_user: admin
reg_user_pass: "r3dh4t1!"
reg_user_sshkey: "/home/vfarias/.ssh/id_rsa.pub"
ssh_host_pub_key_file: /etc/ssh/ssh_host_ecdsa_key.pub

net_name: demo
bridge_name: virbr3
bridge_ip_addr: 192.168.8.1
bridge_netmask: 255.255.255.0
domain_name: example.com

ovirt_engine_setup_admin_password: "r3dh4t1!"


rhvm_repos:
  - rhel-7-server-supplementary-rpms
  - rhel-7-server-rhv-4.2-manager-rpms
  - rhel-7-server-rhv-4-manager-tools-rpms
  - rhel-7-server-ansible-2-rpms
  - jb-eap-7-for-rhel-7-server-rpms

rhvh_repos:
  - rhel-7-server-rhv-4-mgmt-agent-rpms
  - rhel-7-server-ansible-2-rpms

gluster_repos:
  - rh-gluster-3-for-rhel-7-server-rpms

guests:
  gluster01:
    mem: 1024
    cpus: 1
    os_type: rhel7
    file_type: qcow2
    ip_addr: 192.168.8.11
    data_disk_size: 25
    role: gluster
  gluster02:
    mem: 1024
    cpus: 1
    os_type: rhel7
    file_type: qcow2
    ip_addr: 192.168.8.12
    data_disk_size: 25
    role: gluster
  gluster03:
    mem: 1024
    cpus: 1
    os_type: rhel7
    file_type: qcow2
    ip_addr: 192.168.8.13
    data_disk_size: 10
    role: gluster
  rhvm:
    mem: 4096
    cpus: 2
    os_type: rhel7
    file_type: qcow2
    ip_addr: 192.168.8.21
    role: rhvm
  rhvh01:
    mem: 4096
    cpus: 2
    os_type: rhel7
    file_type: qcow2
    ip_addr: 192.168.8.22
    vm_net: "{{ net_name }}"
    role: rhvh
