---
# Disaster Recovery environment tasks
- name: Configure Gluster servers - Disaster Recovery
  hosts: gluster-backup
  become: yes
  remote_user: "{{ reg_user }}"
  vars_files:
    - config-vars.yml

  tasks:
    - name: Update OS
      import_role:
        name: base_os
        tasks_from: prepare.yml

    - name: Install Gluster software
      import_role: 
        name: gluster
        tasks_from: install-gluster.yml

- name: Gdeploy - Disaster Recovery
  hosts: gluster-backup[0]
  remote_user: "{{ reg_user }}"
  #remote_user: admin
  vars_files:
    - config-vars.yml
  tags: gdeploy

  tasks:
    - import_role:
        name: gluster
        tasks_from: install-gdeploy.yml


