---
- block:
  - name: Enable repository
    rhsm_repository: 
      name: rhel-7-server-ansible-2-rpms
    #when: new_register.changed
    tags:
      - repos

  - name: install required packages
    yum:
      name: "{{ item }}"
    with_items:
      - ansible
      - gdeploy

  - name: Copy gdeploy configuration file
    template:
      src: gdeploy.conf.j2
      dest: /root/gdeploy.conf
    tags:
      - gdeployconf

  # TODO: Identify a better way to check if gdeploy was
  # already run
  - name: Check if volumes were already created
    shell: gluster volume info data
    register: volume_exist
    ignore_errors: yes

  - name: Run gdeploy
    command: gdeploy -c /root/gdeploy.conf
    when: volume_exist.rc != 0
  become: yes



