---
- block:
  - name: Enable repository - subscription manager
    rhsm_repository: 
      name: rhel-7-server-ansible-2-rpms
    when: repository == "customer_portal"
    tags:
      - repos

  - name: Enable repository - yum repo
    yum_repository: 
      name: rhel-7-server-ansible-2-rpms
      description: rhel-7-server-ansible-2-rpms
      baseurl: "{{ baseurl }}/rhel-7-server-ansible-2-rpms"
      gpgcheck: no
    when: repository == "yumrepo"
    tags:
      - repos


  - name: install required packages
    yum:
      name: "{{ item }}"
    with_items:
      - ansible
      - gdeploy
    tags:
      - package_install

  - name: Copy gdeploy configuration file
    template:
      src: gdeploy.conf.j2
      dest: /root/gdeploy.conf
    tags:
      - gdeployconf

  # TODO: Identify a better way to check if gdeploy was
  # already run
  - name: Check if volumes were already created
    shell: gluster volume info data
    register: volume_exist
    ignore_errors: yes

  - name: Run gdeploy
    command: gdeploy -c /root/gdeploy.conf
    when: volume_exist.rc != 0
  become: yes



