---
#- name: import subscription manager information
#  include_vars: "rhsm.yml"
#  tags: 
#    - always

- name: register the server
  redhat_subscription:
    state: present
    activationkey: "{{ activation_key }}"
    org_id: "{{ rhsm_org_id }}"
  register: new_register
  when: repository == "customer_portal" 
  tags: 
    - always
    - repos

- name: If first time - Disable all repos
  shell: subscription-manager repos --disable=*
  when: repository == "customer_portal" and (new_register.changed or force_repos)
  tags: 
    - always
    - repos

- name: Enable base repository - subscription manager
  shell: subscription-manager repos --enable rhel-7-server-rpms
  when: repository == "customer_portal" and (new_register.changed or force_repos)
  tags: 
    - always
    - repos

- name: Enable base repository - yum repos
  yum_repository:
    name: rhel-7-server-rpms
    description: rhel-7-server-rpms
    baseurl: "{{ baseurl }}/rhel-7-server-rpms"
    gpgcheck: no
  when: repository == "yumrepo" 
  register: yumrepo
  tags:
    - always
    - repos

## yum update
- name: update packages
  yum:
    name: '*'
    state: latest
  register: package_update
  # Initial update only.
  # Subsequent updates should be handled by another play
  when: new_register.changed or force_repos or yumrepo.changed
  tags:
    - always
    - package_install

#- name: Reboot
#  shell: sleep 5 && reboot
#  async: 30
#  poll: 0
#  ignore_errors: true
#  when: package_update is changed 
#
#- name: Wait for the reboot to complete if there was a change.
#  wait_for_connection:
#    connect_timeout: 20
#    sleep: 5
#    delay: 5
#    timeout: 300
#  when: package_update is changed 
#
